from __future__ import annotations

DECISION_VERSION = "AI_STOCK_DECISION_V3_1_EVENT_OVERLAY_SHADOW"
SCREENING_VERSION = "LLM_SCREENING_V3_1_FRESH_EVENT_OVERLAY_SHADOW"
EVENT_REVIEW_VERSION = "EVENT_REVIEW_V3_FRESHNESS_VERIFIED_OUTCOME_SEPARATED"
SEARCH_CONTRACT_VERSION = "FLASH_DIRECT_SEARCH_CONTRACT_V7_NON_THINKING_SERVER_TOOL_LOOP"
PRODUCTION_OR_SHADOW = "SHADOW"
DIRECT_SEARCH_FALLBACK = "FLASH_V4_DIRECT_SEARCH_FALLBACK"

SEARCH_STATUSES = {
    "VERIFIED_WITH_STRUCTURED_PROVIDER",
    DIRECT_SEARCH_FALLBACK,
    "NO_RESULT_FOUND",
    "NO_MATERIAL_EVENT",
    "NO_SCORE_ELIGIBLE_EVIDENCE",
    "MATERIAL_EVENT_FOUND",
    "SEARCH_FAILED",
    "SEARCH_TIMEOUT",
    "EVIDENCE_CONFLICT",
    "PUBLISH_TIME_UNKNOWN",
    "URL_MISSING",
    "FUTURE_EVIDENCE_REJECTED",
    "HISTORICAL_EVIDENCE_UNAVAILABLE",
}
