CREATE TABLE IF NOT EXISTS market_daily_snapshot (
    id INTEGER PRIMARY KEY,
    trade_date DATE NOT NULL,
    decision_time DATETIME NOT NULL,
    market_direction VARCHAR(16) NOT NULL,
    market_regime VARCHAR(32) NOT NULL,
    regime_score FLOAT NOT NULL,
    regime_confidence FLOAT NOT NULL,
    data_quality_score FLOAT NOT NULL,
    index_summary_json JSON NOT NULL,
    breadth_summary_json JSON NOT NULL,
    turnover_summary_json JSON NOT NULL,
    limit_summary_json JSON NOT NULL,
    industry_summary_json JSON NOT NULL,
    concept_summary_json JSON NOT NULL,
    style_summary_json JSON NOT NULL,
    capital_summary_json JSON NOT NULL,
    technical_summary_json JSON NOT NULL,
    metric_ids_json JSON NOT NULL,
    source_status_json JSON NOT NULL,
    dataset_watermark_hash VARCHAR(64) NOT NULL,
    snapshot_hash VARCHAR(64) NOT NULL,
    schema_version VARCHAR(32) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT uq_market_snapshot_trade_hash UNIQUE (trade_date, snapshot_hash)
);

CREATE TABLE IF NOT EXISTS market_review_evidence (
    id INTEGER PRIMARY KEY,
    evidence_id VARCHAR(64) NOT NULL UNIQUE,
    trade_date DATE NOT NULL,
    title VARCHAR(512) NOT NULL,
    source_name VARCHAR(128) NOT NULL,
    domain VARCHAR(255) NOT NULL,
    canonical_url VARCHAR(1024) NOT NULL,
    publish_time DATETIME,
    fetched_at DATETIME NOT NULL,
    short_summary TEXT NOT NULL,
    source_tier VARCHAR(32) NOT NULL,
    official BOOLEAN NOT NULL,
    direction VARCHAR(16) NOT NULL,
    affected_scope VARCHAR(128) NOT NULL,
    affected_sectors_json JSON NOT NULL,
    credibility_score FLOAT NOT NULL,
    relevance_score FLOAT NOT NULL,
    timeliness_score FLOAT NOT NULL,
    final_evidence_score FLOAT NOT NULL,
    duplicate_group_id VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS market_review_run (
    id INTEGER PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL UNIQUE,
    trade_date DATE NOT NULL,
    status VARCHAR(32) NOT NULL,
    cache_status VARCHAR(32) NOT NULL,
    snapshot_id INTEGER NOT NULL REFERENCES market_daily_snapshot(id),
    search_status VARCHAR(16) NOT NULL,
    evidence_count INTEGER NOT NULL,
    evidence_hash VARCHAR(64) NOT NULL,
    review_input_hash VARCHAR(64) NOT NULL,
    model_alias VARCHAR(128) NOT NULL,
    actual_model VARCHAR(128) NOT NULL,
    prompt_version VARCHAR(64) NOT NULL,
    contract_version VARCHAR(64) NOT NULL,
    market_direction VARCHAR(16) NOT NULL,
    market_regime VARCHAR(32) NOT NULL,
    market_outlook_score FLOAT NOT NULL,
    base_case_probability INTEGER NOT NULL,
    bull_case_probability INTEGER NOT NULL,
    bear_case_probability INTEGER NOT NULL,
    overall_confidence FLOAT NOT NULL,
    data_conflict BOOLEAN NOT NULL,
    review_summary_json JSON NOT NULL,
    token_usage_id INTEGER REFERENCES llm_usage(id),
    pipeline_run_id VARCHAR(128),
    excel_export_status VARCHAR(32) NOT NULL,
    completed_at DATETIME,
    error_message TEXT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS market_review_driver (
    id INTEGER PRIMARY KEY,
    market_review_run_id INTEGER NOT NULL REFERENCES market_review_run(id),
    driver_type VARCHAR(16) NOT NULL,
    title VARCHAR(256) NOT NULL,
    direction VARCHAR(16) NOT NULL,
    impact_strength INTEGER NOT NULL,
    confidence FLOAT NOT NULL,
    affected_scope VARCHAR(128) NOT NULL,
    affected_sectors_json JSON NOT NULL,
    evidence_ids_json JSON NOT NULL,
    metric_ids_json JSON NOT NULL,
    explanation TEXT NOT NULL,
    rank INTEGER NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS market_outlook_scenario (
    id INTEGER PRIMARY KEY,
    market_review_run_id INTEGER NOT NULL REFERENCES market_review_run(id),
    scenario_type VARCHAR(16) NOT NULL,
    probability INTEGER NOT NULL,
    title VARCHAR(128) NOT NULL,
    description TEXT NOT NULL,
    supporting_reasons_json JSON NOT NULL,
    triggers_json JSON NOT NULL,
    invalidation_conditions_json JSON NOT NULL,
    watch_items_json JSON NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT uq_market_outlook_run_type UNIQUE (market_review_run_id, scenario_type)
);
