CREATE TABLE IF NOT EXISTS strategy_timing_contract (
    id INTEGER PRIMARY KEY,
    stock_code VARCHAR(32) NOT NULL,
    trade_date DATE NOT NULL,
    observation_end_ts DATETIME NOT NULL,
    available_at_ts DATETIME NOT NULL,
    signal_generated_at DATETIME NOT NULL,
    order_eligible_at DATETIME NOT NULL,
    execution_policy VARCHAR(64) NOT NULL,
    feature_version VARCHAR(64) NOT NULL,
    data_snapshot_id VARCHAR(128) NOT NULL,
    universe_snapshot_id VARCHAR(128) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT ck_strategy_timing_observation_available CHECK (observation_end_ts <= available_at_ts),
    CONSTRAINT ck_strategy_timing_available_signal CHECK (available_at_ts <= signal_generated_at),
    CONSTRAINT ck_strategy_timing_signal_order CHECK (signal_generated_at < order_eligible_at),
    CONSTRAINT uq_strategy_timing_contract_snapshot UNIQUE (stock_code, trade_date, feature_version, data_snapshot_id, universe_snapshot_id)
);

CREATE TABLE IF NOT EXISTS admission_v3_run (
    id INTEGER PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL UNIQUE,
    trade_date DATE NOT NULL,
    source_v2_run_id VARCHAR(64) NOT NULL,
    quant_run_id VARCHAR(64) NOT NULL,
    input_hash VARCHAR(64) NOT NULL UNIQUE,
    candidate_count INTEGER NOT NULL,
    pass_core_count INTEGER NOT NULL,
    pass_exploratory_count INTEGER NOT NULL,
    review_count INTEGER NOT NULL,
    reject_count INTEGER NOT NULL,
    open_set_count INTEGER NOT NULL,
    config_snapshot JSON NOT NULL,
    status VARCHAR(32) NOT NULL,
    shadow_only BOOLEAN NOT NULL,
    enabled_in_production BOOLEAN NOT NULL,
    quant_hash_before VARCHAR(64) NOT NULL,
    quant_hash_after VARCHAR(64) NOT NULL,
    flash_hash_before VARCHAR(64) NOT NULL,
    flash_hash_after VARCHAR(64) NOT NULL,
    pro_hash_before VARCHAR(64) NOT NULL,
    pro_hash_after VARCHAR(64) NOT NULL,
    llm_call_count INTEGER NOT NULL,
    external_api_call_count INTEGER NOT NULL,
    order_creation_count INTEGER NOT NULL,
    version VARCHAR(64) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS factor_attribution (
    id INTEGER PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    timing_contract_id INTEGER NOT NULL REFERENCES strategy_timing_contract(id),
    stock_code VARCHAR(32) NOT NULL,
    trade_date DATE NOT NULL,
    factor_family VARCHAR(32) NOT NULL,
    raw_signal JSON NOT NULL,
    normalized_score NUMERIC(14,6) NOT NULL,
    score_contribution NUMERIC(14,6) NOT NULL,
    gate_contribution NUMERIC(14,6) NOT NULL,
    rank_contribution NUMERIC(14,6) NOT NULL,
    interaction_note VARCHAR(512) NOT NULL,
    lineage_json JSON NOT NULL,
    version VARCHAR(64) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT uq_factor_attribution_run_stock_family UNIQUE (run_id, stock_code, factor_family)
);

CREATE TABLE IF NOT EXISTS admission_v3_result (
    id INTEGER PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    timing_contract_id INTEGER NOT NULL REFERENCES strategy_timing_contract(id),
    source_v2_run_id VARCHAR(64) NOT NULL,
    stock_code VARCHAR(32) NOT NULL,
    stock_name VARCHAR(128),
    trade_date DATE NOT NULL,
    quant_rank INTEGER,
    industry VARCHAR(128),
    admission_state VARCHAR(32) NOT NULL,
    strategy_status VARCHAR(32) NOT NULL,
    strategy_probability JSON NOT NULL,
    hard_gate_results JSON NOT NULL,
    risk_penalties JSON NOT NULL,
    opportunity_components JSON NOT NULL,
    portfolio_adjustments JSON NOT NULL,
    counterfactuals JSON NOT NULL,
    base_score NUMERIC(14,6) NOT NULL,
    opportunity_score NUMERIC(14,6) NOT NULL,
    final_score NUMERIC(14,6) NOT NULL,
    position_multiplier NUMERIC(14,6) NOT NULL,
    selected_reason VARCHAR(512),
    rejected_reasons JSON NOT NULL,
    largest_factor VARCHAR(32),
    largest_gate VARCHAR(64),
    llm_structured_output JSON NOT NULL,
    final_llm_score NUMERIC(14,6),
    shadow_only BOOLEAN NOT NULL,
    version VARCHAR(64) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT uq_admission_v3_run_stock UNIQUE (run_id, stock_code)
);

CREATE TABLE IF NOT EXISTS gate_evaluation (
    id INTEGER PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    trade_date DATE NOT NULL,
    gate_name VARCHAR(64) NOT NULL,
    blocked_count INTEGER NOT NULL,
    evaluated_count INTEGER NOT NULL,
    future_return NUMERIC(14,6),
    avoided_loss NUMERIC(14,6) NOT NULL,
    missed_gain NUMERIC(14,6) NOT NULL,
    net_gate_value NUMERIC(14,6) NOT NULL,
    counterfactual_json JSON NOT NULL,
    version VARCHAR(64) NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    CONSTRAINT uq_gate_evaluation_run_gate UNIQUE (run_id, gate_name)
);
