CREATE TABLE IF NOT EXISTS midday_recommendation_run (
    id INTEGER PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL UNIQUE,
    session_trade_date DATE NOT NULL,
    decision_time DATETIME NOT NULL,
    market_session VARCHAR(32) NOT NULL,
    baseline_trade_date DATE,
    baseline_quant_run_id VARCHAR(64),
    baseline_manifest_id VARCHAR(64),
    status VARCHAR(40) NOT NULL,
    current_stage VARCHAR(40) NOT NULL,
    target_session VARCHAR(32) NOT NULL,
    valid_from DATETIME NOT NULL,
    valid_until DATETIME NOT NULL,
    recheck_required BOOLEAN NOT NULL,
    source_mode VARCHAR(80) NOT NULL,
    base_pool_count INTEGER NOT NULL DEFAULT 0,
    snapshot_count INTEGER NOT NULL DEFAULT 0,
    minute_count INTEGER NOT NULL DEFAULT 0,
    flash_count INTEGER NOT NULL DEFAULT 0,
    pro_count INTEGER NOT NULL DEFAULT 0,
    final_count INTEGER NOT NULL DEFAULT 0,
    held_count INTEGER NOT NULL DEFAULT 0,
    token_usage INTEGER NOT NULL DEFAULT 0,
    cost NUMERIC(18,8) NOT NULL DEFAULT 0,
    total_duration_ms INTEGER NOT NULL DEFAULT 0,
    input_hash VARCHAR(64) NOT NULL UNIQUE,
    config_snapshot JSON NOT NULL,
    checkpoint_json JSON NOT NULL,
    excel_path VARCHAR(512),
    completed_at DATETIME,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS midday_recommendation_result (
    id INTEGER PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    stock_code VARCHAR(32) NOT NULL,
    stock_name VARCHAR(128),
    pool_sources JSON NOT NULL,
    position_status VARCHAR(32) NOT NULL,
    base_quant_score NUMERIC(12,6) NOT NULL,
    base_quant_rank INTEGER NOT NULL,
    feature_scope VARCHAR(32) NOT NULL,
    midday_overlay_score NUMERIC(12,6),
    midday_delta NUMERIC(12,6) NOT NULL,
    midday_enhanced_score NUMERIC(12,6) NOT NULL,
    quick_snapshot_rank INTEGER,
    minute_rank INTEGER,
    midday_flash_score NUMERIC(12,6),
    flash_decision VARCHAR(24),
    midday_pro_score NUMERIC(12,6),
    pro_rank INTEGER,
    hard_gate_status VARCHAR(32) NOT NULL,
    candidate_action VARCHAR(40) NOT NULL,
    held_action VARCHAR(40),
    recommended_price NUMERIC(16,6),
    max_acceptable_price NUMERIC(16,6),
    stop_loss NUMERIC(16,6),
    take_profit_1 NUMERIC(16,6),
    take_profit_2 NUMERIC(16,6),
    suggested_weight NUMERIC(18,10),
    suggested_position_percent NUMERIC(18,10),
    valid_until DATETIME NOT NULL,
    recheck_required BOOLEAN NOT NULL,
    key_reasons JSON NOT NULL,
    key_risks JSON NOT NULL,
    data_quality JSON NOT NULL,
    requires_manual_review BOOLEAN NOT NULL,
    actionable BOOLEAN NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE(run_id, stock_code)
);

CREATE TABLE IF NOT EXISTS midday_recheck_result (
    id INTEGER PRIMARY KEY,
    midday_run_id VARCHAR(64) NOT NULL,
    stock_code VARCHAR(32) NOT NULL,
    recheck_time DATETIME NOT NULL,
    latest_price NUMERIC(16,6),
    index_status VARCHAR(32) NOT NULL,
    freshness VARCHAR(32) NOT NULL,
    price_deviation NUMERIC(18,10),
    hard_gate_status VARCHAR(32) NOT NULL,
    recheck_status VARCHAR(32) NOT NULL,
    invalidation_reason TEXT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE(midday_run_id, stock_code, recheck_time)
);
