-- Advisory-only iFinD Shadow scoring and post-close action snapshots.
-- No production ranking, order, trade, or scheduler tables are modified.

CREATE TABLE IF NOT EXISTS ifind_enhancement_run (
    id INTEGER PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL UNIQUE,
    trade_date DATE NOT NULL,
    quant_run_id VARCHAR(64) NOT NULL,
    provider_run_id VARCHAR(64),
    mode VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    input_hash VARCHAR(64) NOT NULL UNIQUE,
    stock_count INTEGER NOT NULL DEFAULT 0,
    coverage_ratio NUMERIC(18,10) NOT NULL DEFAULT 0,
    material_conflict_count INTEGER NOT NULL DEFAULT 0,
    feature_version VARCHAR(64) NOT NULL,
    scoring_profile VARCHAR(32) NOT NULL,
    cohort_snapshot_json JSON NOT NULL,
    completed_at DATETIME,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS ifind_stock_enhancement_score (
    id INTEGER PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    stock_code VARCHAR(32) NOT NULL,
    base_score NUMERIC(12,6) NOT NULL,
    base_rank INTEGER NOT NULL,
    ifind_eod_score NUMERIC(12,6),
    overlay_delta NUMERIC(12,6) NOT NULL DEFAULT 0,
    enhanced_score NUMERIC(12,6) NOT NULL,
    enhanced_rank INTEGER NOT NULL,
    relative_strength_score NUMERIC(12,6),
    close_quality_score NUMERIC(12,6),
    tail_strength_score NUMERIC(12,6),
    intraday_stability_score NUMERIC(12,6),
    liquidity_confirmation_score NUMERIC(12,6),
    regime_fit_score NUMERIC(12,6),
    component_scores_json JSON NOT NULL,
    data_quality_coefficient NUMERIC(18,10) NOT NULL DEFAULT 0,
    freshness_status VARCHAR(32) NOT NULL,
    minute_completeness NUMERIC(18,10),
    dual_source_status VARCHAR(32) NOT NULL,
    scoring_profile VARCHAR(32) NOT NULL,
    feature_version VARCHAR(64) NOT NULL,
    fallback_reason VARCHAR(64),
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE (run_id, stock_code)
);

CREATE TABLE IF NOT EXISTS trader_position_snapshot (
    id INTEGER PRIMARY KEY,
    account_scope VARCHAR(32) NOT NULL,
    snapshot_time DATETIME NOT NULL,
    trade_date DATE NOT NULL,
    stock_code VARCHAR(32) NOT NULL,
    stock_name_snapshot VARCHAR(128),
    quantity INTEGER NOT NULL,
    available_quantity INTEGER NOT NULL,
    cost_price NUMERIC(16,6) NOT NULL,
    buy_date DATE,
    market_value NUMERIC(20,4),
    position_percent NUMERIC(18,10),
    source VARCHAR(32) NOT NULL,
    version VARCHAR(64) NOT NULL,
    is_current BOOLEAN NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE (account_scope, version, stock_code)
);

CREATE TABLE IF NOT EXISTS trader_position_import_batch (
    id INTEGER PRIMARY KEY,
    preview_id VARCHAR(64) NOT NULL UNIQUE,
    account_scope VARCHAR(32) NOT NULL,
    source_filename VARCHAR(255) NOT NULL,
    payload_hash VARCHAR(64) NOT NULL,
    rows_json JSON NOT NULL,
    status VARCHAR(32) NOT NULL,
    error_json JSON NOT NULL,
    confirmed_at DATETIME,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS position_truth_confirmation (
    id INTEGER PRIMARY KEY,
    account_scope VARCHAR(32) NOT NULL,
    trade_date DATE NOT NULL,
    snapshot_time DATETIME NOT NULL,
    position_count INTEGER NOT NULL,
    confirmation_status VARCHAR(32) NOT NULL,
    confirmed_by VARCHAR(64) NOT NULL,
    snapshot_version VARCHAR(64) NOT NULL,
    snapshot_hash VARCHAR(64) NOT NULL UNIQUE,
    is_current BOOLEAN NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_position_truth_current ON position_truth_confirmation (account_scope, is_current);

CREATE TABLE IF NOT EXISTS post_close_action_run (
    id INTEGER PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL UNIQUE,
    trade_date DATE NOT NULL,
    target_trade_date DATE NOT NULL,
    run_mode VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    pipeline_run_id VARCHAR(128),
    quant_run_id VARCHAR(64),
    enhancement_run_id VARCHAR(64),
    position_snapshot_id VARCHAR(64),
    market_review_run_id VARCHAR(64),
    input_hash VARCHAR(64) NOT NULL UNIQUE,
    stock_count INTEGER NOT NULL DEFAULT 0,
    held_count INTEGER NOT NULL DEFAULT 0,
    non_held_count INTEGER NOT NULL DEFAULT 0,
    rule_duration_ms INTEGER NOT NULL DEFAULT 0,
    pro_review_status VARCHAR(32) NOT NULL,
    scoring_profile VARCHAR(32) NOT NULL,
    config_snapshot_json JSON NOT NULL,
    completed_at DATETIME,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS post_close_action_result (
    id INTEGER PRIMARY KEY,
    run_id VARCHAR(64) NOT NULL,
    stock_code VARCHAR(32) NOT NULL,
    stock_name VARCHAR(128),
    selection_source VARCHAR(128) NOT NULL,
    position_status VARCHAR(32) NOT NULL,
    account_scope VARCHAR(32),
    quantity INTEGER,
    available_quantity INTEGER,
    target_day_sellable_quantity INTEGER,
    cost_price NUMERIC(16,6),
    close_price NUMERIC(16,6),
    unrealized_return NUMERIC(18,10),
    holding_days INTEGER,
    base_score NUMERIC(12,6),
    ifind_shadow_score NUMERIC(12,6),
    enhanced_shadow_score NUMERIC(12,6),
    base_rank INTEGER,
    enhanced_rank INTEGER,
    action_health_score NUMERIC(12,6),
    baseline_rule_action VARCHAR(64) NOT NULL,
    ifind_shadow_action VARCHAR(64) NOT NULL,
    pro_review_action VARCHAR(64),
    current_adopted_action VARCHAR(64) NOT NULL,
    current_position_percent NUMERIC(18,10),
    suggested_target_position_percent NUMERIC(18,10),
    suggested_reduce_percent NUMERIC(18,10),
    suggested_reduce_quantity INTEGER,
    stop_loss_price NUMERIC(16,6),
    take_profit_1 NUMERIC(16,6),
    take_profit_2 NUMERIC(16,6),
    hard_gate_status VARCHAR(64) NOT NULL,
    key_reasons_json JSON NOT NULL,
    key_risks_json JSON NOT NULL,
    data_quality_status VARCHAR(32) NOT NULL,
    requires_manual_review BOOLEAN NOT NULL DEFAULT 0,
    advice_version VARCHAR(64) NOT NULL,
    review_reason TEXT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    UNIQUE (run_id, stock_code)
);
