import { defineStore } from "pinia";

export type LanguageCode = "en" | "zh-CN";

interface LanguageOption {
  value: LanguageCode;
  label: string;
  nativeLabel: string;
}

const STORAGE_KEY = "ai_trader_language";

export const languageOptions: LanguageOption[] = [
  { value: "en", label: "English", nativeLabel: "English" },
  { value: "zh-CN", label: "Chinese", nativeLabel: "中文" }
];

const messages: Record<LanguageCode, Record<string, string>> = {
  en: {
    "brand.controlPanel": "Control Panel",
    "common.actions": "Actions",
    "common.amount": "Amount",
    "common.cancel": "Cancel",
    "common.changed": "changed",
    "common.closed": "Closed",
    "common.code": "Code",
    "common.confidence": "Confidence",
    "common.connected": "connected",
    "common.createdAt": "Created At",
    "common.direction": "Direction",
    "common.disable": "Disable",
    "common.disconnected": "disconnected",
    "common.enabled": "Enabled",
    "common.failed": "failed",
    "common.healthy": "Healthy",
    "common.id": "ID",
    "common.layer": "Layer",
    "common.message": "Message",
    "common.modified": "modified",
    "common.name": "Name",
    "common.noRows": "No data",
    "common.price": "Price",
    "common.provider": "Provider",
    "common.quality": "Quality",
    "common.qty": "Qty",
    "common.rank": "Rank",
    "common.reason": "Reason",
    "common.refresh": "Refresh",
    "common.reset": "Reset",
    "common.riskLevel": "Risk Level",
    "common.save": "Save",
    "common.status": "Status",
    "common.summary": "Summary",
    "common.title": "Title",
    "common.type": "Type",
    "common.unknown": "unknown",
    "common.user": "User",
    "config.changeReason": "change reason",
    "config.noEditable": "No editable config",
    "config.riskAlert": "Risk controls affect alerts and cancellation advice only. Real trading remains blocked.",
    "dashboard.backendHealth": "Backend Health",
    "dashboard.checkBackend": "Check backend status",
    "dashboard.database": "Database",
    "dashboard.dataSourceMode": "Data Source Mode",
    "dashboard.llmMode": "LLM Mode",
    "dashboard.localMockOnly": "local mock-only",
    "dashboard.mockDataActive": "Mock Provider active",
    "dashboard.mockLlmActive": "Mock LLM active",
    "dashboard.packagingDetail": "No real trading, no broker, no real LLM",
    "dashboard.packagingMode": "Packaging Mode",
    "dashboard.prepared": "prepared",
    "dashboard.startupDetail": "Backend 127.0.0.1:8000, frontend 127.0.0.1:5173",
    "dashboard.startupMode": "Startup Mode",
    "dashboard.subtitle": "Operational overview for mock-only AI trading assistance.",
    "dashboard.title": "Dashboard",
    "dailyReview.finalReviewScore": "Final Review Score",
    "dailyReview.maxDrawdown": "Max Drawdown",
    "dailyReview.mistakeAnalysis": "Mistake Analysis",
    "dailyReview.orderPriceQuality": "Order Price Quality",
    "dailyReview.predictionAccuracy": "Prediction Accuracy",
    "dailyReview.profitLoss": "Profit/Loss",
    "dailyReview.run": "Run Daily Review",
    "dailyReview.suggestion": "Suggestion",
    "dailyReview.winRate": "Win Rate",
    "dataSources.mockQuotes": "Mock quotes",
    "dataSources.mockStocks": "Mock stocks",
    "dataSources.title": "Data Sources",
    "language.label": "Language",
    "memory.alert": "Vector and graph memory remain disabled in Phase 14.",
    "memory.conflict": "Conflict",
    "memory.create": "Create Memory",
    "memory.createContent": "Manual frontend memory note for advisory context only.",
    "memory.createSummary": "frontend memory",
    "memory.createTitle": "Frontend note",
    "memory.graphEnabled": "graph_enabled",
    "memory.keyword": "keyword",
    "memory.markConflict": "Conflict",
    "memory.memoryType": "memory_type",
    "memory.midTermTtlDays": "mid_term_ttl_days",
    "memory.minQualityScore": "min_quality_score",
    "memory.noNotes": "No memory notes",
    "memory.playbooks": "Playbooks",
    "memory.reflectionFromReview": "Reflection from review",
    "memory.reuse": "Reuse",
    "memory.search": "Search Memory",
    "memory.shortTermTtlHours": "short_term_ttl_hours",
    "memory.stockCode": "stock_code",
    "memory.topK": "top_k",
    "memory.vectorEnabled": "vector_enabled",
    "model.agent": "Agent",
    "model.agentRoutes": "Agent Routes",
    "model.alert": "Real model providers and provider credentials are disabled in this phase.",
    "model.configSaved": "LLM config saved.",
    "model.costBudgetUsd": "cost_budget_usd",
    "model.defaultModel": "default_model",
    "model.defaultProvider": "default_provider",
    "model.disabledProvider": "real provider disabled",
    "model.error": "Model request failed",
    "model.maxTokens": "max_tokens",
    "model.mockOnly": "mock_only",
    "model.noProviders": "No providers",
    "model.providerList": "Provider List",
    "model.saveConfirm": "Save LLM mock config to database config?",
    "model.selection": "Selection",
    "model.subtitle": "Phase 14 allows Mock Provider and Mock LLM only.",
    "model.temperature": "temperature",
    "model.tokenBudget": "token_budget",
    "model.usageSummary": "Usage Summary",
    "nav.alertsCenter": "Alerts Center",
    "nav.aiCommittee": "AI Committee",
    "nav.dailyReview": "Daily Review",
    "nav.dashboard": "Dashboard",
    "nav.dataSources": "Data Sources",
    "nav.lightScreening": "Light Screening",
    "nav.memoryConsole": "Memory Console",
    "nav.modelManagement": "Model Management",
    "nav.orderPricePlans": "Order Price Plans",
    "nav.preMarketRecheck": "Pre-market Recheck",
    "nav.quantScan": "Quant Scan",
    "nav.systemConfig": "System Config",
    "nav.systemStatus": "System Status",
    "nav.virtualTrading": "Virtual Trading",
    "notFound.back": "Back to Dashboard",
    "notFound.title": "Page not found",
    "order.generate": "Generate Order Plans",
    "order.high": "High",
    "order.low": "Low",
    "order.maxAcceptable": "Max Acceptable",
    "order.recommended": "Recommended",
    "order.stopLoss": "Stop Loss",
    "order.takeProfit1": "Take Profit 1",
    "order.takeProfit2": "Take Profit 2",
    "preMarket.newPrice": "New Price",
    "preMarket.oldPrice": "Old Price",
    "preMarket.planId": "Plan ID",
    "preMarket.run": "Run Pre-market Recheck",
    "quant.capital": "Capital",
    "quant.emotion": "Emotion",
    "quant.finalScore": "Final Score",
    "quant.industry": "Industry",
    "quant.light": "Light",
    "quant.momentum": "Momentum",
    "quant.quant": "Quant",
    "quant.recommendation": "Recommendation",
    "quant.runCommittee": "Run Committee",
    "quant.runLightScreening": "Run Light Screening",
    "quant.runQuantScan": "Run Quant Scan",
    "quant.risk": "Risk",
    "quant.riskNote": "Risk Note",
    "quant.technical": "Technical",
    "quant.total": "Total",
    "quant.controllerReason": "Controller Reason",
    "safety.safe": "Real trading is off. Packaged builds also remain Mock Provider + Mock LLM + AI Simulation only.",
    "safety.unsafe": "Backend reports real_trading_enabled=true. Trading actions are blocked in this frontend.",
    "shortcut.alertsMeta": "Intraday scan",
    "shortcut.aiSimulationAccount": "AI Simulation Account",
    "shortcut.committeeMeta": "Mock LLM committee",
    "shortcut.dailyReviewMeta": "Post-market evaluation",
    "shortcut.memoryMeta": "Database memory",
    "shortcut.orderPlansMeta": "Advisory price plans",
    "shortcut.quantMeta": "Run quant ranking",
    "shortcut.systemStatusMeta": "Safety summary",
    "shortcut.virtualMeta": "Virtual trading only",
    "status.api": "API",
    "status.connected": "Connected",
    "status.data": "Data",
    "status.disconnected": "Disconnected",
    "status.llm": "LLM",
    "status.noTrace": "no-trace",
    "systemConfig.configHistory": "config_history",
    "systemConfig.dataSource": "Data Source",
    "systemConfig.error": "Config request failed",
    "systemConfig.errorRealTrading": "real_trading_enabled=true was reported. Config saves are blocked.",
    "systemConfig.key": "Key",
    "systemConfig.llmMode": "LLM Mode",
    "systemConfig.new": "New",
    "systemConfig.noHistory": "No config history",
    "systemConfig.old": "Old",
    "systemConfig.priority": "Priority",
    "systemConfig.realTrading": "real_trading_enabled",
    "systemConfig.resetConfirm": "Confirm Config Reset",
    "systemConfig.resetPromptPrefix": "Reset",
    "systemConfig.resetPromptSuffix": "to config file/default value?",
    "systemConfig.resetSuccess": "Config reset.",
    "systemConfig.saveConfirm": "Confirm Config Save",
    "systemConfig.savePromptPrefix": "Save",
    "systemConfig.savePromptSuffix": "changes to database config and config_history?",
    "systemConfig.saveSuccess": "Config saved.",
    "systemConfig.subtitle": "Web UI overrides are persisted to database and recorded in config_history.",
    "systemConfig.time": "Time",
    "systemConfig.title": "System Config",
    "systemStatus.apiBase": "API Base",
    "systemStatus.apiBaseDetail": "Packaged shell connects locally",
    "systemStatus.blockedByFrontend": "Blocked by frontend",
    "systemStatus.dataSources": "Data Sources",
    "systemStatus.deployment": "Deployment",
    "systemStatus.deploymentDetail": "Backend runs as local process",
    "systemStatus.localDesktopPrep": "local desktop prep",
    "systemStatus.mockOnly": "Mock only",
    "systemStatus.mockProvider": "Mock provider",
    "systemStatus.realTrading": "Real Trading",
    "systemStatus.reviewBackend": "Review backend config",
    "virtual.actions": "Virtual Actions",
    "virtual.alertSafe": "AI Simulation mode only. real_trading_enabled=false.",
    "virtual.alertUnsafe": "Virtual trading controls are disabled because backend safety status is unsafe.",
    "virtual.allowPartialFill": "allow_partial_fill",
    "virtual.cancelOrder": "Cancel virtual order",
    "virtual.cancelSuccess": "Virtual order cancel request sent.",
    "virtual.cash": "Cash",
    "virtual.commissionRate": "commission_rate",
    "virtual.createAccount": "Create AI Simulation Account",
    "virtual.initialCash": "initial_cash",
    "virtual.latest": "Latest",
    "virtual.marketValue": "Market Value",
    "virtual.noOrders": "No virtual orders",
    "virtual.noPositions": "No virtual positions",
    "virtual.noTrades": "No virtual trades",
    "virtual.orders": "Orders",
    "virtual.positions": "Positions",
    "virtual.repriceOrder": "Reprice virtual order",
    "virtual.repriceSuccess": "Virtual order reprice request sent.",
    "virtual.runPlans": "Run AI Simulation Plans",
    "virtual.slippageRate": "slippage_rate",
    "virtual.stampTaxRate": "stamp_tax_rate",
    "virtual.totalAsset": "Total Asset",
    "virtual.trades": "Trades"
  },
  "zh-CN": {
    "brand.controlPanel": "控制台",
    "common.actions": "操作",
    "common.amount": "金额",
    "common.cancel": "取消",
    "common.changed": "已变更",
    "common.closed": "已关闭",
    "common.code": "代码",
    "common.confidence": "置信度",
    "common.connected": "已连接",
    "common.createdAt": "创建时间",
    "common.direction": "方向",
    "common.disable": "禁用",
    "common.disconnected": "未连接",
    "common.enabled": "启用",
    "common.failed": "失败",
    "common.healthy": "健康",
    "common.id": "ID",
    "common.layer": "层级",
    "common.message": "消息",
    "common.modified": "已修改",
    "common.name": "名称",
    "common.noRows": "暂无数据",
    "common.price": "价格",
    "common.provider": "提供方",
    "common.quality": "质量",
    "common.qty": "数量",
    "common.rank": "排名",
    "common.reason": "原因",
    "common.refresh": "刷新",
    "common.reset": "重置",
    "common.riskLevel": "风险等级",
    "common.save": "保存",
    "common.status": "状态",
    "common.summary": "摘要",
    "common.title": "标题",
    "common.type": "类型",
    "common.unknown": "未知",
    "common.user": "用户",
    "config.changeReason": "变更原因",
    "config.noEditable": "暂无可编辑配置",
    "config.riskAlert": "风控配置只影响提醒和撤单建议，真实交易仍保持禁用。",
    "dashboard.backendHealth": "后端健康",
    "dashboard.checkBackend": "请检查后端状态",
    "dashboard.database": "数据库",
    "dashboard.dataSourceMode": "数据源模式",
    "dashboard.llmMode": "LLM 模式",
    "dashboard.localMockOnly": "本地 mock-only",
    "dashboard.mockDataActive": "Mock Provider 已启用",
    "dashboard.mockLlmActive": "Mock LLM 已启用",
    "dashboard.packagingDetail": "无真实交易、无券商接口、无真实 LLM",
    "dashboard.packagingMode": "打包模式",
    "dashboard.prepared": "已准备",
    "dashboard.startupDetail": "后端 127.0.0.1:8000，前端 127.0.0.1:5173",
    "dashboard.startupMode": "启动模式",
    "dashboard.subtitle": "面向 mock-only AI 交易辅助的运行概览。",
    "dashboard.title": "仪表盘",
    "dailyReview.finalReviewScore": "最终复盘分",
    "dailyReview.maxDrawdown": "最大回撤",
    "dailyReview.mistakeAnalysis": "错误分析",
    "dailyReview.orderPriceQuality": "挂单价质量",
    "dailyReview.predictionAccuracy": "预测准确率",
    "dailyReview.profitLoss": "盈亏",
    "dailyReview.run": "运行每日复盘",
    "dailyReview.suggestion": "建议",
    "dailyReview.winRate": "胜率",
    "dataSources.mockQuotes": "Mock 行情",
    "dataSources.mockStocks": "Mock 股票",
    "dataSources.title": "数据源",
    "language.label": "语言",
    "memory.alert": "向量记忆和图记忆在 Phase 14 仍保持禁用。",
    "memory.conflict": "冲突",
    "memory.create": "创建记忆",
    "memory.createContent": "前端手动记忆，仅用于辅助上下文。",
    "memory.createSummary": "前端记忆",
    "memory.createTitle": "前端笔记",
    "memory.graphEnabled": "图记忆启用",
    "memory.keyword": "关键词",
    "memory.markConflict": "标记冲突",
    "memory.memoryType": "记忆类型",
    "memory.midTermTtlDays": "中期记忆保留天数",
    "memory.minQualityScore": "最低质量分",
    "memory.noNotes": "暂无记忆笔记",
    "memory.playbooks": "经验库",
    "memory.reflectionFromReview": "从复盘生成反思",
    "memory.reuse": "复用",
    "memory.search": "搜索记忆",
    "memory.shortTermTtlHours": "短期记忆保留小时",
    "memory.stockCode": "股票代码",
    "memory.topK": "召回数量",
    "memory.vectorEnabled": "向量记忆启用",
    "model.agent": "Agent",
    "model.agentRoutes": "Agent 路由",
    "model.alert": "本阶段禁用真实模型提供方和真实凭据。",
    "model.configSaved": "LLM 配置已保存。",
    "model.costBudgetUsd": "美元成本预算",
    "model.defaultModel": "默认模型",
    "model.defaultProvider": "默认提供方",
    "model.disabledProvider": "真实提供方已禁用",
    "model.error": "模型请求失败",
    "model.maxTokens": "最大 tokens",
    "model.mockOnly": "仅 Mock",
    "model.noProviders": "暂无提供方",
    "model.providerList": "提供方列表",
    "model.saveConfirm": "保存 LLM mock 配置到数据库配置？",
    "model.selection": "选择",
    "model.subtitle": "Phase 14 仅允许 Mock Provider 和 Mock LLM。",
    "model.temperature": "temperature",
    "model.tokenBudget": "token 预算",
    "model.usageSummary": "用量摘要",
    "nav.alertsCenter": "盘中预警",
    "nav.aiCommittee": "AI 委员会",
    "nav.dailyReview": "每日复盘",
    "nav.dashboard": "仪表盘",
    "nav.dataSources": "数据源",
    "nav.lightScreening": "轻量筛选",
    "nav.memoryConsole": "记忆控制台",
    "nav.modelManagement": "模型管理",
    "nav.orderPricePlans": "挂单价计划",
    "nav.preMarketRecheck": "盘前复核",
    "nav.quantScan": "量化扫描",
    "nav.systemConfig": "系统配置",
    "nav.systemStatus": "系统状态",
    "nav.virtualTrading": "虚拟盘",
    "notFound.back": "返回仪表盘",
    "notFound.title": "页面未找到",
    "order.generate": "生成挂单价计划",
    "order.high": "上限",
    "order.low": "下限",
    "order.maxAcceptable": "最高可接受价",
    "order.recommended": "建议价",
    "order.stopLoss": "止损价",
    "order.takeProfit1": "止盈 1",
    "order.takeProfit2": "止盈 2",
    "preMarket.newPrice": "新建议价",
    "preMarket.oldPrice": "旧建议价",
    "preMarket.planId": "计划 ID",
    "preMarket.run": "运行盘前复核",
    "quant.capital": "资金",
    "quant.emotion": "情绪",
    "quant.finalScore": "最终分",
    "quant.industry": "行业",
    "quant.light": "轻筛分",
    "quant.momentum": "动量",
    "quant.quant": "量化",
    "quant.recommendation": "建议",
    "quant.runCommittee": "运行委员会",
    "quant.runLightScreening": "运行轻量筛选",
    "quant.runQuantScan": "运行量化扫描",
    "quant.risk": "风险",
    "quant.riskNote": "风险说明",
    "quant.technical": "技术",
    "quant.total": "总分",
    "quant.controllerReason": "控制器理由",
    "safety.safe": "真实交易已关闭。打包版本也仅保留 Mock Provider + Mock LLM + AI Simulation。",
    "safety.unsafe": "后端报告 real_trading_enabled=true，前端已阻止交易操作。",
    "shortcut.alertsMeta": "盘中扫描",
    "shortcut.aiSimulationAccount": "AI 模拟账户",
    "shortcut.committeeMeta": "Mock LLM 委员会",
    "shortcut.dailyReviewMeta": "盘后评估",
    "shortcut.memoryMeta": "数据库记忆",
    "shortcut.orderPlansMeta": "辅助挂单价计划",
    "shortcut.quantMeta": "运行量化排名",
    "shortcut.systemStatusMeta": "安全摘要",
    "shortcut.virtualMeta": "仅虚拟交易",
    "status.api": "API",
    "status.connected": "已连接",
    "status.data": "数据",
    "status.disconnected": "未连接",
    "status.llm": "LLM",
    "status.noTrace": "无 trace",
    "systemConfig.configHistory": "配置历史",
    "systemConfig.dataSource": "数据源",
    "systemConfig.error": "配置请求失败",
    "systemConfig.errorRealTrading": "检测到 real_trading_enabled=true，已阻止配置保存。",
    "systemConfig.key": "配置键",
    "systemConfig.llmMode": "LLM 模式",
    "systemConfig.new": "新值",
    "systemConfig.noHistory": "暂无配置历史",
    "systemConfig.old": "旧值",
    "systemConfig.priority": "优先级",
    "systemConfig.realTrading": "real_trading_enabled",
    "systemConfig.resetConfirm": "确认重置配置",
    "systemConfig.resetPromptPrefix": "是否将",
    "systemConfig.resetPromptSuffix": "重置为配置文件/默认值？",
    "systemConfig.resetSuccess": "配置已重置。",
    "systemConfig.saveConfirm": "确认保存配置",
    "systemConfig.savePromptPrefix": "保存",
    "systemConfig.savePromptSuffix": "变更到数据库配置和 config_history？",
    "systemConfig.saveSuccess": "配置已保存。",
    "systemConfig.subtitle": "Web UI 覆盖项会持久化到数据库，并写入 config_history。",
    "systemConfig.time": "时间",
    "systemConfig.title": "系统配置",
    "systemStatus.apiBase": "API 地址",
    "systemStatus.apiBaseDetail": "打包壳连接本地服务",
    "systemStatus.blockedByFrontend": "已被前端阻止",
    "systemStatus.dataSources": "数据源",
    "systemStatus.deployment": "部署",
    "systemStatus.deploymentDetail": "后端以本地进程运行",
    "systemStatus.localDesktopPrep": "本地桌面准备",
    "systemStatus.mockOnly": "仅 Mock",
    "systemStatus.mockProvider": "Mock Provider",
    "systemStatus.realTrading": "真实交易",
    "systemStatus.reviewBackend": "请检查后端配置",
    "virtual.actions": "虚拟操作",
    "virtual.alertSafe": "仅 AI Simulation 模式，real_trading_enabled=false。",
    "virtual.alertUnsafe": "后端安全状态不安全，虚拟盘控制已禁用。",
    "virtual.allowPartialFill": "允许部分成交",
    "virtual.cancelOrder": "撤销虚拟订单",
    "virtual.cancelSuccess": "虚拟订单撤销请求已发送。",
    "virtual.cash": "现金",
    "virtual.commissionRate": "佣金率",
    "virtual.createAccount": "创建 AI 模拟账户",
    "virtual.initialCash": "初始资金",
    "virtual.latest": "最新价",
    "virtual.marketValue": "市值",
    "virtual.noOrders": "暂无虚拟订单",
    "virtual.noPositions": "暂无虚拟持仓",
    "virtual.noTrades": "暂无虚拟成交",
    "virtual.orders": "订单",
    "virtual.positions": "持仓",
    "virtual.repriceOrder": "调整虚拟订单价格",
    "virtual.repriceSuccess": "虚拟订单改价请求已发送。",
    "virtual.runPlans": "运行 AI 模拟计划",
    "virtual.slippageRate": "滑点率",
    "virtual.stampTaxRate": "印花税率",
    "virtual.totalAsset": "总资产",
    "virtual.trades": "成交"
  }
};

const categoryMessages: Record<LanguageCode, Record<string, string>> = {
  en: {
    llm: "LLM Mock Config",
    memory: "Memory",
    order_price: "Order Price",
    quant_weights: "Quant Weights",
    refresh_frequency: "Refresh Frequency",
    risk_alert: "Risk Alerts",
    stock_scan: "Stock Scan",
    virtual_trading: "Virtual Trading"
  },
  "zh-CN": {
    llm: "LLM Mock 配置",
    memory: "记忆参数",
    order_price: "挂单价参数",
    quant_weights: "量化权重",
    refresh_frequency: "刷新频率",
    risk_alert: "风控提醒阈值",
    stock_scan: "股票筛选参数",
    virtual_trading: "虚拟盘参数"
  }
};

export type MessageKey = string;

export const useLanguageStore = defineStore("language", {
  state: () => ({
    current: initialLanguage()
  }),
  getters: {
    options: () => languageOptions,
    t: (state) => (key: MessageKey): string => {
      return messages[state.current][key] || messages.en[key] || key;
    },
    categoryLabel: (state) => (category: string): string => {
      return categoryMessages[state.current][category] || categoryMessages.en[category] || category;
    },
    displayValue: (state) => (value: unknown): string => {
      const text = String(value || "unknown");
      return text === "unknown" ? messages[state.current]["common.unknown"] : text;
    }
  },
  actions: {
    setLanguage(value: unknown) {
      this.current = normalizeLanguage(value);
      if (typeof window !== "undefined") {
        window.localStorage.setItem(STORAGE_KEY, this.current);
      }
    }
  }
});

function initialLanguage(): LanguageCode {
  if (typeof window === "undefined") {
    return "en";
  }
  return normalizeLanguage(window.localStorage.getItem(STORAGE_KEY));
}

function normalizeLanguage(value: unknown): LanguageCode {
  return value === "zh-CN" ? "zh-CN" : "en";
}
